config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  get 'contact', to: 'contact#index'

  get 'team',          to: 'team_members#index',   as: :team_members
  get 'team/new',      to: 'team_members#new',     as: :new_team_member
  get 'team/:id',      to: 'team_members#show',    as: :team_member
  get 'team/:id/edit', to: 'team_members#edit',    as: :edit_team_member
  match 'team',        to: 'team_members#create',  via: :post
  match 'team/:id',    to: 'team_members#update',  via: :patch
  match 'team/:id',    to: 'team_members#destroy', as: :delete_team_member, via: :delete

  get 'blog',               to: 'blog_articles#index',     as: :blog_articles
  get 'blog/new',           to: 'blog_articles#new',       as: :blog_article_new
  get 'blog/:id',           to: 'blog_articles#show',      as: :blog_article
  get 'blog/:id/edit',      to: 'blog_articles#edit',      as: :blog_article_edit
  get 'blog/:id/publish',   to: 'blog_articles#publish',   as: :blog_article_publish
  get 'blog/:id/unpublish', to: 'blog_articles#unpublish', as: :blog_article_unpublish
  match 'blog',             to: 'blog_articles#create',    via: :post
  match 'blog/:id',         to: 'blog_articles#destroy',   as: :blog_article_delete, via: :delete
  match 'blog/:id',         to: 'blog_articles#update',    via: :patch

  get 'jobs',          to: 'jobs#index', as: :jobs
  get 'jobs/new',      to: 'jobs#new',   as: :job_new
  get 'jobs/:id',      to: 'jobs#show',  as: :job
  get 'jobs/:id/edit', to: 'jobs#edit',  as: :job_edit
  match 'jobs',        to: 'jobs#create', via: :post
  match 'jobs/:id',    to: 'jobs#update', via: :patch
  match 'jobs/:id',    to: 'jobs#destroy', as: :job_delete, via: :delete

  get 'job-locations',          to: 'job_locations#index',   as: :job_locations
  get 'job-locations/new',      to: 'job_locations#new',     as: :job_locations_new
  get 'job-locations/:id',       to: 'job_locations#show',     as: :job_location
  get 'job-locations/:id/edit', to: 'job_locations#edit',    as: :job_location_edit
  match 'job-locations',        to: 'job_locations#create',  via: :post
  match 'job-locations/:id',    to: 'job_locations#destroy', as: :job_location_delete, via: :delete
  match 'job-locations/:id',     to: 'job_locations#update',  via: :patch

  get 'products',         to: 'products#index',   as: :products
  get 'products/new',      to: 'products#new',     as: :products_new
  get 'products/:id',      to: 'products#show',    as: :product
  get 'products/:id/edit', to: 'products#edit',    as: :product_edit
  match 'products',        to: 'products#create',  via: :post
  match 'products/:id',    to: 'products#destroy', as: :product_delete, via: :delete
  match 'products/:id',    to: 'products#update',  via: :patch

  get 'products/:product_id/specification/:specification_id',           to: 'products#new_specification',     as: :product_product_specification
  get 'products/:id/specifications',                                    to: 'products#index_specification',   as: :product_specifications
  get 'products/:id/add-specification',                                 to: 'products#new_specification',     as: :product_add_specification
  get 'products/:product_id/specifications/:specification_id/edit',     to: 'products#edit_specification',    as: :product_edit_specification
  match 'products/:product_id/specifications/:specification_id/delete', to: 'products#destroy_specification', as: :product_delete_specification, via: :delete
  match 'products/:id/specifications',                                  to: 'products#create_specification',  via: :post
  match 'products/:product_id/specifications/:specification_id',        to: 'products#update_specification',  via: :patch

  get 'products/:product_id/reviews/:review_id',                to: 'product_reviews#new',     as: :product_product_review
  get 'products/:id/reviews',                                   to: 'product_reviews#index',   as: :product_product_reviews
  match 'products/:product_id/reviews/:review_id/delete',       to: 'product_reviews#destroy', as: :delete_product_review, via: :delete
  match 'products/:id/reviews',                                 to: 'product_reviews#create',  via: :post
  match 'products/:product_id/reviews/:review_id',              to: 'product_reviews#update',  via: :patch

  get 'products/:id/images',                           to: 'product#index_images',  as: :product_product_images
  get 'products/:product_id/image/:image_id',          to: 'products#show_image',   as: :product_product_image
  get 'products/:id/add-image',                        to: 'products#new_image',    as: :product_add_image
  get 'products/:product_id/image/:image_id/edit',     to: 'products#edit_image',   as: :product_edit_image
  match 'products/:product_id/image/:image_id/delete', to: 'products#destroy_image', as: :product_delete_image, via: :delete
  match 'products/:id/images',                         to: 'products#create_image', via: :post
  match 'products/:product_id/image/:image_id',        to: 'products#update_image', via: :patch

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :job_location

  validates :title,           presence: true, length: { maximum: 150 }
  validates :subtitle,        presence: true, length: { maximum: 150 }
  validates :body,            presence: true
  validates :apply_url,       presence: true
  validates :job_location_id, presence: true

  def to_param
    [id, title.parameterize].join('-')
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: %w( new create edit update destroy )

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      flash[:success] = 'Job created'
      redirect_to jobs_path
    else
      render :new
    end
  end

  def index
    redirect_to job_path Job.first if Job.first.present?
    @job_locations = JobLocation.all.order(:title)
  end

  def show
    @job_locations = JobLocation.all.order(:title)
    @job = Job.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        autolink: true,
                                        space_after_headers: true,
                                        fenced_code_blocks: true,
                                        prettify: true)
    @breadcrumb_components.last[:name] = @job.title
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(job_params)
      flash[:success] = 'Job updated'
      redirect_to job_path @job
    else
      render :edit
    end
  end

  def destroy
    if Job.find(params[:id]).destroy
      redirect_to jobs_path
      flash[:success] = 'Job successfully deleted'
    else
      redirect_to jobs_path
      flash[:warning] = 'Problem deleting Job'
    end
  end

  private

    def job_params
      params.require(:job).permit(:title, :subtitle, :body, :apply_url,
                                  :job_location_id)
    end
end

app/views/jobs/edit.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @job, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :subtitle, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :subtitle, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :body, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :body, rows: 10, class: 'form-control', id: 'editor' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :apply_url, 'Apply URL', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.url_field :apply_url, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_location, 'Job Location', class: 'col-sm-2 control-label' %><br>
        <div class="col-sm-10">
          <%= f.collection_select :job_location_id, JobLocation.all, :id, :title, prompt: 'Select location...', class: 'form-control select-form-control' %>
          <%= link_to 'Add/Edit Job Locations', job_locations_path, class: 'job-location-helper-link' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Update', class: 'btn btn-bg bg-sea form-button' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/jobs/index.html.erb
<section class="section-4">
  <div class="container">

    <% if user_signed_in? %>
      <div class="pull-right action-bar">
        <%= link_to job_locations_path, class: 'btn btn-bg bg-sea' do %>
          <i class="fa fa-link"></i>
          Manage Job Locations
        <% end %>

        <%= link_to job_new_path, class: 'btn btn-bg bg-green' do %>
          <i class="fa fa-plus"></i>
          New Job
        <% end %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-5 col-md-4">
        <aside class="sidebar-jobs">
          <ul class="jobs-list mb50">
            <% @job_locations.each do |job_location| %>
              <li class="job-location"><%= job_location.title %></li>

              <% if job_location.jobs.any? %>
                <% job_location.jobs.each do |job| %>
                  <li>
                    <%= link_to job.title, job %>
                    <% if user_signed_in? %>
                      <%= link_to 'Edit', job_edit_path(job), style: 'color:red;' %>
                    <% end %>
                  </li>
                <% end %>
              <% else %>
                <li class="text-warning">No open positions.</li>
              <% end %>
            <% end %>
          </ul>
        </aside>
      </div>
      <div class="col-sm-7 col-md-8 space-left">
        <div class="row">
          <p>There are currently no jobs available, please check back later.</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/jobs/new.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @job, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :subtitle, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :subtitle, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :body, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :body, rows: 10, class: 'form-control', id: 'editor' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :apply_url, 'Apply URL', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.url_field :apply_url, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_location, 'Job Location', class: 'col-sm-2 control-label' %><br>
        <div class="col-sm-10">
          <%= f.collection_select :job_location_id, JobLocation.all, :id, :title, prompt: 'Select location...', class: 'form-control select-form-control' %>
          <%= link_to 'Add/Edit Job Locations', job_locations_path, class: 'job-location-helper-link' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Create', class: 'btn btn-bg bg-sea form-button' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/jobs/show.html.erb
<section class="section-4">
  <div class="container">

    <% if user_signed_in? %>
      <div class="pull-right action-bar">
        <%= link_to job_locations_path, class: 'btn btn-bg bg-sea' do %>
          <i class="fa fa-link"></i>
          Manage Job Locations
        <% end %>

        <%= link_to job_edit_path(@job), class: 'btn btn-bg bg-sea' do %>
          <i class="fa fa-pencil"></i>
          Edit Job
        <% end %>

        <%= link_to job_new_path, class: 'btn btn-bg bg-green' do %>
          <i class="fa fa-plus"></i>
          Add New Job
        <% end %>

        <%= link_to job_delete_path(@job), method: :delete, class: 'btn btn-bg bg-red' do %>
          <i class="fa fa-times"></i>
          Delete Job
        <% end %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-5 col-md-4">
        <aside class="sidebar-jobs">
          <ul class="jobs-list mb50">
            <% @job_locations.each do |job_location| %>
              <li class="job-location"><%= job_location.title %></li>

              <% if job_location.jobs.any? %>
                <% job_location.jobs.each do |job| %>
                  <li>
                    <%= link_to job.title, job %>
                    <% if user_signed_in? %>
                      <%= link_to 'Edit', job_edit_path(job), style: 'color:red;' %>
                    <% end %>
                  </li>
                <% end %>
              <% else %>
                <li class="text-warning">No open positions.</li>
              <% end %>
            <% end %>
          </ul>
        </aside>
      </div>
      <div class="col-sm-7 col-md-8 space-left">
        <div class="row">
          <div class="col-sm-12">
            <h2 class="section-title-2">
              <%= @job.title %>

              <small class="pull-right location">
                <i class="fa fa-map-marker"></i>
                <%= @job.job_location.title %>
              </small>
            </h2>
            <h3 class="box-title"><%= @job.subtitle %></h3>
            <%= @markdown.render(@job.body).html_safe %>
            <p class="mt40"><a href="<%= @job.apply_url %>" class="btn voyo-btn-2 br2">Apply Now</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>