config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  get 'contact', to: 'contact#index'

  get 'team',          to: 'team_members#index',   as: :team_members
  get 'team/new',      to: 'team_members#new',     as: :new_team_member
  get 'team/:id',      to: 'team_members#show',    as: :team_member
  get 'team/:id/edit', to: 'team_members#edit',    as: :edit_team_member
  match 'team',        to: 'team_members#create',  via: :post
  match 'team/:id',    to: 'team_members#update',  via: :patch
  match 'team/:id',    to: 'team_members#destroy', as: :delete_team_member, via: :delete

  get 'blog',               to: 'blog_articles#index',     as: :blog_articles
  get 'blog/new',           to: 'blog_articles#new',       as: :blog_article_new
  get 'blog/:id',           to: 'blog_articles#show',      as: :blog_article
  get 'blog/:id/edit',      to: 'blog_articles#edit',      as: :blog_article_edit
  get 'blog/:id/publish',   to: 'blog_articles#publish',   as: :blog_article_publish
  get 'blog/:id/unpublish', to: 'blog_articles#unpublish', as: :blog_article_unpublish
  match 'blog',             to: 'blog_articles#create',    via: :post
  match 'blog/:id',         to: 'blog_articles#destroy',   as: :blog_article_delete, via: :delete
  match 'blog/:id',         to: 'blog_articles#update',    via: :patch

  get 'jobs',          to: 'jobs#index', as: :jobs
  get 'jobs/new',      to: 'jobs#new',   as: :job_new
  get 'jobs/:id',      to: 'jobs#show',  as: :job
  get 'jobs/:id/edit', to: 'jobs#edit',  as: :job_edit
  match 'jobs',        to: 'jobs#create', via: :post
  match 'jobs/:id',    to: 'jobs#update', via: :patch
  match 'jobs/:id',    to: 'jobs#destroy', as: :job_delete, via: :delete

  get 'job-locations',          to: 'job_locations#index',   as: :job_locations
  get 'job-locations/new',      to: 'job_locations#new',     as: :job_locations_new
  get 'job-locations/:id',       to: 'job_locations#show',     as: :job_location
  get 'job-locations/:id/edit', to: 'job_locations#edit',    as: :job_location_edit
  match 'job-locations',        to: 'job_locations#create',  via: :post
  match 'job-locations/:id',    to: 'job_locations#destroy', as: :job_location_delete, via: :delete
  match 'job-locations/:id',     to: 'job_locations#update',  via: :patch

  get 'products',         to: 'products#index',   as: :products
  get 'products/new',      to: 'products#new',     as: :products_new
  get 'products/:id',      to: 'products#show',    as: :product
  get 'products/:id/edit', to: 'products#edit',    as: :product_edit
  match 'products',        to: 'products#create',  via: :post
  match 'products/:id',    to: 'products#destroy', as: :product_delete, via: :delete
  match 'products/:id',    to: 'products#update',  via: :patch

  get 'products/:product_id/specification/:specification_id',           to: 'products#new_specification',     as: :product_product_specification
  get 'products/:id/specifications',                                    to: 'products#index_specification',   as: :product_specifications
  get 'products/:id/add-specification',                                 to: 'products#new_specification',     as: :product_add_specification
  get 'products/:product_id/specifications/:specification_id/edit',     to: 'products#edit_specification',    as: :product_edit_specification
  match 'products/:product_id/specifications/:specification_id/delete', to: 'products#destroy_specification', as: :product_delete_specification, via: :delete
  match 'products/:id/specifications',                                  to: 'products#create_specification',  via: :post
  match 'products/:product_id/specifications/:specification_id',        to: 'products#update_specification',  via: :patch

  get 'products/:product_id/reviews/:review_id',                to: 'product_reviews#new',     as: :product_product_review
  get 'products/:id/reviews',                                   to: 'product_reviews#index',   as: :product_product_reviews
  match 'products/:product_id/reviews/:review_id/delete',       to: 'product_reviews#destroy', as: :delete_product_review, via: :delete
  match 'products/:id/reviews',                                 to: 'product_reviews#create',  via: :post
  match 'products/:product_id/reviews/:review_id',              to: 'product_reviews#update',  via: :patch

  get 'products/:id/images',                           to: 'product#index_images',  as: :product_product_images
  get 'products/:product_id/image/:image_id',          to: 'products#show_image',   as: :product_product_image
  get 'products/:id/add-image',                        to: 'products#new_image',    as: :product_add_image
  get 'products/:product_id/image/:image_id/edit',     to: 'products#edit_image',   as: :product_edit_image
  match 'products/:product_id/image/:image_id/delete', to: 'products#destroy_image', as: :product_delete_image, via: :delete
  match 'products/:id/images',                         to: 'products#create_image', via: :post
  match 'products/:product_id/image/:image_id',        to: 'products#update_image', via: :patch

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :job_title,  presence: true
  validates :order,      presence: true
  validates :avatar,     attachment_presence: true

  def name
    "#{first_name} #{last_name}"
  end

  def to_param
    [id, first_name.parameterize, last_name.parameterize].join('-')
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :authenticate_user!, except: %w( index show )

  def index
    @team_members = TeamMember.all.order(:order)
  end

  def new
    @team_member = TeamMember.new
  end

  def create
    @team_member = TeamMember.new(team_member_params)

    if @team_member.save
      flash[:success] = 'Team Member created'
      redirect_to team_members_path
    else
      render :new
    end
  end

  def edit
    @team_member = TeamMember.find(params[:id])
  end

  def update
    @team_members = TeamMember.find(params[:id])

    if @team_members.update_attributes(team_member_params)
      flash[:success] = 'Team Member updated'
      redirect_to team_members_path
    else
      render :edit
    end
  end

  def destroy
    if TeamMember.find(params[:id]).destroy
      redirect_to team_members_path
      flash[:success] = 'Team Member successfully deleted'
    else
      redirect_to team_members_path
      flash[:warning] = 'Problem deleting Team Member'
    end
  end

  private

    def team_member_params
      params.require(:team_member).permit(:first_name, :last_name,
                                          :contact_email, :job_title,
                                          :short_info, :avatar, :order)
    end
end

app/views/team_members/edit.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @team_member, class: 'form' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :first_name, 'First Name', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :first_name, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, 'Last Name', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :contact_email, 'Contact Email', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.email_field :contact_email, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_title, 'Job Title', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :job_title, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :short_info, 'Short Info', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :short_info, rows: 5, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :order, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :order, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :avatar, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Update', class: 'btn btn-bg bg-sea form-button' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/team_members/index.html.erb
<section class="section-3 custom-bg large-padding parallax mt0" data-bg="<%= image_path 'voyo/demo/a-101.jpg' %>">
  <div class="bg-layer"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-8">
        <div class="box-about">
          <h2 class="section-title st2 text-left mb30"><%= edit_text(@page, 'team_members_page_image_title', 'Everyone wants to join our Team') %></h2>
          <p class="custom-bg-p mb10"><%= edit_text(@page, 'team_members_page_image_body') %></p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3 sm-box2">
        <div class="box-content">
          <%= image_tag 'voyo/icons/full-color/128px/volume.png' %>
          <h3><%= edit_text(@page, 'team_members_page_infographic_title_1', 'Inspiring') %></h3>
          <p><%= edit_text(@page, 'team_members_page_infographic_body_1') %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3 sm-box2">
        <div class="box-content">
          <%= image_tag 'voyo/icons/full-color/128px/takeoff.png' %>
          <h3><%= edit_text(@page, 'team_members_page_infographic_title_2', 'Empowering') %></h3>
          <p><%= edit_text(@page, 'team_members_page_infographic_body_2') %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3 xs-box2">
        <div class="box-content">
          <%= image_tag 'voyo/icons/full-color/128px/trophy.png' %>
          <h3><%= edit_text(@page, 'team_members_page_infographic_title_3', 'Rewarding') %></h3>
          <p><%= edit_text(@page, 'team_members_page_infographic_body_3') %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="box-content">
          <%= image_tag 'voyo/icons/full-color/128px/rgb.png' %>
          <h3><%= edit_text(@page, 'team_members_page_infographic_title_4', 'Fun') %></h3>
          <p><%= edit_text(@page, 'team_members_page_infographic_body_4') %></p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section-3 section-dark mb0">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <h2 class="section-title st2 mb25"><%= edit_text(@page, 'team_members_page_wide_title', 'What\'s it like working for us?') %></h2>
        <div class="text-center">
          <p class="mb0"><%= edit_text(@page, 'team_members_page_wide_body') %></p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section team-section mb30">
  <div class="container">
    <div class="row">
      <% if user_signed_in? %>
        <div class="pull-right action-bar">
          <%= link_to new_team_member_path, class: 'btn btn-bg bg-green' do %>
            <i class="fa fa-plus"></i>
            New Team Member
          <% end %>
        </div>
      <% end %>

      <h3 class="center our-team__header"><%= edit_text(@page, 'team_members_page_our_team_header', 'Our Team') %></h3>

      <% @team_members.each do |team_member| %>
        <div class="col-sm-6 xs-box2 team-member-container">
          <% if user_signed_in? %>
            <div class="pull-right">
              <%= link_to delete_team_member_path(team_member), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-bg bg-red' do %>
                Delete
              <% end %>
              <%= link_to edit_team_member_path(team_member), class: 'btn btn-bg bg-sea' do %>
                Edit
              <% end %>
            </div>
          <% end %>

          <div class="box-team">
            <div class="team-image">
              <%= image_tag team_member.avatar.url, alt: 'team' %>
            </div>
            <div class="team-info">
              <h3><%= team_member.name %></h3>
              <h5><%= team_member.job_title %></h5>
              <p><%= team_member.short_info %></p>
            </div>
          </div> <!-- END Person -->
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/team_members/new.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @team_member, class: 'form' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :first_name, 'First Name', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :first_name, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, 'Last Name', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :contact_email, 'Contact Email', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.email_field :contact_email, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_title, 'Job Title', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :job_title, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :short_info, 'Short Info', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :short_info, rows: 5, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :order, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :order, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :avatar, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Create', class: 'btn btn-bg bg-sea form-button' %>
        </div>
      </div>
    <% end %>
  </div>
</section>