config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  get 'contact', to: 'contact#index'

  get 'team',          to: 'team_members#index',   as: :team_members
  get 'team/new',      to: 'team_members#new',     as: :new_team_member
  get 'team/:id',      to: 'team_members#show',    as: :team_member
  get 'team/:id/edit', to: 'team_members#edit',    as: :edit_team_member
  match 'team',        to: 'team_members#create',  via: :post
  match 'team/:id',    to: 'team_members#update',  via: :patch
  match 'team/:id',    to: 'team_members#destroy', as: :delete_team_member, via: :delete

  get 'blog',               to: 'blog_articles#index',     as: :blog_articles
  get 'blog/new',           to: 'blog_articles#new',       as: :blog_article_new
  get 'blog/:id',           to: 'blog_articles#show',      as: :blog_article
  get 'blog/:id/edit',      to: 'blog_articles#edit',      as: :blog_article_edit
  get 'blog/:id/publish',   to: 'blog_articles#publish',   as: :blog_article_publish
  get 'blog/:id/unpublish', to: 'blog_articles#unpublish', as: :blog_article_unpublish
  match 'blog',             to: 'blog_articles#create',    via: :post
  match 'blog/:id',         to: 'blog_articles#destroy',   as: :blog_article_delete, via: :delete
  match 'blog/:id',         to: 'blog_articles#update',    via: :patch

  get 'jobs',          to: 'jobs#index', as: :jobs
  get 'jobs/new',      to: 'jobs#new',   as: :job_new
  get 'jobs/:id',      to: 'jobs#show',  as: :job
  get 'jobs/:id/edit', to: 'jobs#edit',  as: :job_edit
  match 'jobs',        to: 'jobs#create', via: :post
  match 'jobs/:id',    to: 'jobs#update', via: :patch
  match 'jobs/:id',    to: 'jobs#destroy', as: :job_delete, via: :delete

  get 'job-locations',          to: 'job_locations#index',   as: :job_locations
  get 'job-locations/new',      to: 'job_locations#new',     as: :job_locations_new
  get 'job-locations/:id',       to: 'job_locations#show',     as: :job_location
  get 'job-locations/:id/edit', to: 'job_locations#edit',    as: :job_location_edit
  match 'job-locations',        to: 'job_locations#create',  via: :post
  match 'job-locations/:id',    to: 'job_locations#destroy', as: :job_location_delete, via: :delete
  match 'job-locations/:id',     to: 'job_locations#update',  via: :patch

  get 'products',         to: 'products#index',   as: :products
  get 'products/new',      to: 'products#new',     as: :products_new
  get 'products/:id',      to: 'products#show',    as: :product
  get 'products/:id/edit', to: 'products#edit',    as: :product_edit
  match 'products',        to: 'products#create',  via: :post
  match 'products/:id',    to: 'products#destroy', as: :product_delete, via: :delete
  match 'products/:id',    to: 'products#update',  via: :patch

  get 'products/:product_id/specification/:specification_id',           to: 'products#new_specification',     as: :product_product_specification
  get 'products/:id/specifications',                                    to: 'products#index_specification',   as: :product_specifications
  get 'products/:id/add-specification',                                 to: 'products#new_specification',     as: :product_add_specification
  get 'products/:product_id/specifications/:specification_id/edit',     to: 'products#edit_specification',    as: :product_edit_specification
  match 'products/:product_id/specifications/:specification_id/delete', to: 'products#destroy_specification', as: :product_delete_specification, via: :delete
  match 'products/:id/specifications',                                  to: 'products#create_specification',  via: :post
  match 'products/:product_id/specifications/:specification_id',        to: 'products#update_specification',  via: :patch

  get 'products/:product_id/reviews/:review_id',                to: 'product_reviews#new',     as: :product_product_review
  get 'products/:id/reviews',                                   to: 'product_reviews#index',   as: :product_product_reviews
  match 'products/:product_id/reviews/:review_id/delete',       to: 'product_reviews#destroy', as: :delete_product_review, via: :delete
  match 'products/:id/reviews',                                 to: 'product_reviews#create',  via: :post
  match 'products/:product_id/reviews/:review_id',              to: 'product_reviews#update',  via: :patch

  get 'products/:id/images',                           to: 'product#index_images',  as: :product_product_images
  get 'products/:product_id/image/:image_id',          to: 'products#show_image',   as: :product_product_image
  get 'products/:id/add-image',                        to: 'products#new_image',    as: :product_add_image
  get 'products/:product_id/image/:image_id/edit',     to: 'products#edit_image',   as: :product_edit_image
  match 'products/:product_id/image/:image_id/delete', to: 'products#destroy_image', as: :product_delete_image, via: :delete
  match 'products/:id/images',                         to: 'products#create_image', via: :post
  match 'products/:product_id/image/:image_id',        to: 'products#update_image', via: :patch

end

app/models/blog_article.rb
class BlogArticle < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_attached_file :image, default_url: "/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title,        presence: true
  validates :body,         presence: true
  validates :author_id,    presence: true
  validates :image,        attachment_presence: true

  def to_param
    [id, title.parameterize].join('-')
  end
end

app/controllers/blog_articles_controller.rb
class BlogArticlesController < ApplicationController
  before_action :authenticate_user!, only: %w( new create edit update destroy )

  def new
    @blog_article = BlogArticle.new
  end

  def create
    @blog_article = BlogArticle.new(
      blog_article_params.merge({ author_id: current_user.id, is_published: false })
    )

    if @blog_article.save
      flash[:success] = 'Blog Article created'
      redirect_to blog_path
    else
      render :new
    end
  end

  def index
    @page_title = 'Blog'

    if user_signed_in?
      @blog_articles = BlogArticle.all.order('created_at desc')
    else
      @blog_articles = BlogArticle.all.where(is_published: true).order('created_at desc')
    end
  end

  def show
    @blog_article = BlogArticle.find(params[:id])

    render_404 if !@blog_article.is_published && !user_signed_in?

    @page_title = "#{@blog_article.title} - Blog"
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        autolink: true,
                                        space_after_headers: true,
                                        fenced_code_blocks: true,
                                        prettify: true)

    @sidebar_blog_articles = BlogArticle.where(is_published: true).last(3).reverse

    @breadcrumb_components.last[:name] = @blog_article.title
  end

  def edit
    @blog_article = BlogArticle.find(params[:id])
    @page_title = @blog_article.title

    @breadcrumb_components[2][:name] = @blog_article.title
  end

  def update
    @blog_article = BlogArticle.find(params[:id])

    if @blog_article.update_attributes(blog_article_params)
      flash[:success] = 'Blog Article updated'
      redirect_to blog_article_path @blog_article
    else
      render :edit
    end
  end

  def destroy
  end

  def publish
    @blog_article = BlogArticle.find(params[:id])
    @blog_article.is_published = true

    if @blog_article.save
      flash[:success] = 'Article published'
    else
      flash[:warning] = 'Error publishing Article'
    end

    redirect_to request.referrer
  end

  def unpublish
    @blog_article = BlogArticle.find(params[:id])
    @blog_article.is_published = false

    if @blog_article.save
      flash[:success] = 'Article Unpublished'
    else
      flash[:warning] = 'Error unpublishing Article'
    end

    redirect_to request.referrer
  end

  private

    def blog_article_params
      params.require(:blog_article).permit(:title, :body, :short_description,
                                           :image)
    end
end

app/views/blog_articles/edit.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @blog_article, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <label class="col-sm-2 control-label">Author</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= current_user.name %></p>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :image, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, class: 'form-control', placeholder: 'Image' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :short_description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :short_description, class: 'form-control', placeholder: 'Short Description' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :body, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Body', id: 'editor' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Update", class: 'btn btn-bg bg-sea' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/blog_articles/index.html.erb
<section class="section-4">
  <div class="container">
    <div class="row">
      <% if user_signed_in? %>
        <div class="pull-right action-bar">
          <%= link_to blog_article_new_path, class: 'btn btn-bg bg-green' do %>
            <i class="fa fa-plus"></i>
            New Blog Article
          <% end %>
        </div>
      <% end %>
      <div class="col-sm-12">
        <div id="portfolio-isotope">
          <div class="portfolio-container">
            <div class="row">
              <div class="portfolio">
                <% @blog_articles.each do |blog_article| %>
                  <div class="col-sm-6 col-md-4 el animated" data-anim="fadeInUp">
                    <div class="blog-item">
                      <% if user_signed_in? && !blog_article.is_published %>
                        <div class="unpublished-banner">Unpublished</div>
                      <% end %>
                      <div class="blog-image">
                        <% if blog_article.image.url != '/missing.png' %>
                          <%= image_tag blog_article.image.url %>
                        <% end %>
                      </div>
                      <div class="blog-caption">
                        <h3 class="post-title"><%= blog_article.title %></h3>
                        <div class="sub-post-title">
                          <span><%= blog_article.created_at.strftime("%e %b %Y") %></span>
                          <span>
                            <i class="fa fa-user"></i>
                            <%= link_to "by #{blog_article.author.name}", '#' %>
                          </span>
                        </div>
                        <p><%= blog_article.body %></p>
                        <%= link_to 'Read more', blog_article_path(blog_article), class: 'read-more' %>
                      </div>
                    </div>
                  </div> <!-- END Blog Item -->
                <% end %>
              </div> <!-- END portfolio Blog -->
            </div>
          </div> <!-- END portfolio Container -->
        </div> <!-- END Portfolio Isotope -->
      </div>
    </div>
  </div>
</section> <!-- END Blog Page-->

app/views/blog_articles/new.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @blog_article, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <label class="col-sm-2 control-label">Author</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= current_user.name %></p>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :image, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, class: 'form-control', placeholder: 'Image' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :short_description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :short_description, class: 'form-control', placeholder: 'Short Description' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :body, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Body', id: 'editor' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Publish", class: 'btn btn-bg bg-sea' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/blog_articles/show.html.erb
<section class="section-4">
  <div class="container">
    <% if user_signed_in? %>
      <div class="pull-right edit-blog-container action-bar">
        <%= link_to blog_article_edit_path(@blog_article), class: 'btn btn-bg bg-sea' do %>
          <i class="fa fa-pencil"></i>
          Edit Blog Article
        <% end %>

        <% if @blog_article.is_published %>
          <%= link_to blog_article_unpublish_path(@blog_article), class: 'btn btn-bg bg-orange' do %>
            <i class="fa fa-times"></i>
            Unpublish Article
          <% end %>
        <% else %>
          <%= link_to blog_article_publish_path(@blog_article), class: 'btn btn-bg bg-green' do %>
            <i class="fa fa-check"></i>
            Publish Article
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-9 col-md-push-3 space-left ">
        <div id="blog-posts">
          <article class="row blog-item">
            <div class="col-sm-12 blog-image full-image">
              <% if @blog_article.image.url != '/missing.png' %>
                <%= image_tag @blog_article.image.url %>
              <% end %>
            </div>
            <div class="col-sm-12 blog-caption">
              <h2 class="blog-post-title"><%= @blog_article.title %></h2>
              <div class="sub-post-title mb25">
                <span class="date"><%= @blog_article.created_at.strftime("%e %b %Y") %></span>
                <span class="author">
                  <i class="fa fa-user"></i>
                  <%= link_to "by #{@blog_article.author.name}", '#' %>
                </span>
              </div>
              <div class="post-content">
                <%= @markdown.render(@blog_article.body).html_safe %>
              </div>
            </div>
          </article>
          <div class="row blog-item mb50">
            <div class="col-sm-12 blog-caption">
              <div class="media">
                  <div class="pull-left hidden-xs">
                    <%= image_tag @blog_article.author.avatar.url, class: 'media-object author-img img-circle' %>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading"><a href="#" class="user"><%= @blog_article.author.name %></a></h4>
                    <p><%= @blog_article.author.info %></p>
                  </div>
              </div>
            </div>
          </div>
        </div> <!-- END Blog Posts -->
      </div>
      <div class="col-sm-12 col-md-3 col-md-pull-9 ">
        <aside class="sidebar sidebar-3">
          <div class="sidebar-widget">
            <h3 class="sidebar-title"><%= edit_text(@page, 'blog_sidebar_title', 'The Blog') %></h3>
            <p><%= edit_text(@page, 'blog_sidebar_body', 'Take a look at our blog to kepp up-to-date with all the latest company news....') %></p>
          </div>
          <div class="sidebar-widget">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab1" data-toggle="tab">Latest Posts</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane fade in active" id="tab1">
                <ul class="latest-posts">
                  <% @sidebar_blog_articles.each do |blog_article| %>
                    <li>
                      <div class="image-post">
                        <% if blog_article.image.url != '/missing.png' %>
                          <%= image_tag blog_article.image.url %>
                        <% end %>
                      </div>
                      <div class="info-post">
                        <h5><%= link_to blog_article.title, blog_article_path(blog_article) %></h5>
                        <span><%= blog_article.created_at.strftime("%e %b %Y") %> </span>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  </div>
</section>