config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  get 'contact', to: 'contact#index'

  get 'team',          to: 'team_members#index',   as: :team_members
  get 'team/new',      to: 'team_members#new',     as: :new_team_member
  get 'team/:id',      to: 'team_members#show',    as: :team_member
  get 'team/:id/edit', to: 'team_members#edit',    as: :edit_team_member
  match 'team',        to: 'team_members#create',  via: :post
  match 'team/:id',    to: 'team_members#update',  via: :patch
  match 'team/:id',    to: 'team_members#destroy', as: :delete_team_member, via: :delete

  get 'blog',               to: 'blog_articles#index',     as: :blog_articles
  get 'blog/new',           to: 'blog_articles#new',       as: :blog_article_new
  get 'blog/:id',           to: 'blog_articles#show',      as: :blog_article
  get 'blog/:id/edit',      to: 'blog_articles#edit',      as: :blog_article_edit
  get 'blog/:id/publish',   to: 'blog_articles#publish',   as: :blog_article_publish
  get 'blog/:id/unpublish', to: 'blog_articles#unpublish', as: :blog_article_unpublish
  match 'blog',             to: 'blog_articles#create',    via: :post
  match 'blog/:id',         to: 'blog_articles#destroy',   as: :blog_article_delete, via: :delete
  match 'blog/:id',         to: 'blog_articles#update',    via: :patch

  get 'jobs',          to: 'jobs#index', as: :jobs
  get 'jobs/new',      to: 'jobs#new',   as: :job_new
  get 'jobs/:id',      to: 'jobs#show',  as: :job
  get 'jobs/:id/edit', to: 'jobs#edit',  as: :job_edit
  match 'jobs',        to: 'jobs#create', via: :post
  match 'jobs/:id',    to: 'jobs#update', via: :patch
  match 'jobs/:id',    to: 'jobs#destroy', as: :job_delete, via: :delete

  get 'job-locations',          to: 'job_locations#index',   as: :job_locations
  get 'job-locations/new',      to: 'job_locations#new',     as: :job_locations_new
  get 'job-locations/:id',       to: 'job_locations#show',     as: :job_location
  get 'job-locations/:id/edit', to: 'job_locations#edit',    as: :job_location_edit
  match 'job-locations',        to: 'job_locations#create',  via: :post
  match 'job-locations/:id',    to: 'job_locations#destroy', as: :job_location_delete, via: :delete
  match 'job-locations/:id',     to: 'job_locations#update',  via: :patch

  get 'products',         to: 'products#index',   as: :products
  get 'products/new',      to: 'products#new',     as: :products_new
  get 'products/:id',      to: 'products#show',    as: :product
  get 'products/:id/edit', to: 'products#edit',    as: :product_edit
  match 'products',        to: 'products#create',  via: :post
  match 'products/:id',    to: 'products#destroy', as: :product_delete, via: :delete
  match 'products/:id',    to: 'products#update',  via: :patch

  get 'products/:product_id/specification/:specification_id',           to: 'products#new_specification',     as: :product_product_specification
  get 'products/:id/specifications',                                    to: 'products#index_specification',   as: :product_specifications
  get 'products/:id/add-specification',                                 to: 'products#new_specification',     as: :product_add_specification
  get 'products/:product_id/specifications/:specification_id/edit',     to: 'products#edit_specification',    as: :product_edit_specification
  match 'products/:product_id/specifications/:specification_id/delete', to: 'products#destroy_specification', as: :product_delete_specification, via: :delete
  match 'products/:id/specifications',                                  to: 'products#create_specification',  via: :post
  match 'products/:product_id/specifications/:specification_id',        to: 'products#update_specification',  via: :patch

  get 'products/:product_id/reviews/:review_id',                to: 'product_reviews#new',     as: :product_product_review
  get 'products/:id/reviews',                                   to: 'product_reviews#index',   as: :product_product_reviews
  match 'products/:product_id/reviews/:review_id/delete',       to: 'product_reviews#destroy', as: :delete_product_review, via: :delete
  match 'products/:id/reviews',                                 to: 'product_reviews#create',  via: :post
  match 'products/:product_id/reviews/:review_id',              to: 'product_reviews#update',  via: :patch

  get 'products/:id/images',                           to: 'product#index_images',  as: :product_product_images
  get 'products/:product_id/image/:image_id',          to: 'products#show_image',   as: :product_product_image
  get 'products/:id/add-image',                        to: 'products#new_image',    as: :product_add_image
  get 'products/:product_id/image/:image_id/edit',     to: 'products#edit_image',   as: :product_edit_image
  match 'products/:product_id/image/:image_id/delete', to: 'products#destroy_image', as: :product_delete_image, via: :delete
  match 'products/:id/images',                         to: 'products#create_image', via: :post
  match 'products/:product_id/image/:image_id',        to: 'products#update_image', via: :patch

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_specifications, dependent: :destroy
  has_many :product_images,         dependent: :destroy
  has_many :product_reviews,        dependent: :destroy

  validates :name,         presence: true, length: { maximum: 250 }
  validates :user_id,      presence: true
  validates :introduction,                 length: { maximum: 250 }

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %w( index show )

  def index
    @products = Product.all
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        autolink: true,
                                        space_after_headers: true,
                                        fenced_code_blocks: true,
                                        prettify: true)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params.merge({ user_id: current_user.id }))

    if @product.save
      flash[:success] = 'Product saved'
      redirect_to product_path @product
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @review = ProductReview.new
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        autolink: true,
                                        space_after_headers: true,
                                        fenced_code_blocks: true,
                                        prettify: true)

    @breadcrumb_components.last[:name] = @product.name
  end

  def edit
    @product = Product.find(params[:id])

    @breadcrumb_components[-2][:name] = @product.name
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params.merge({ user_id: current_user.id }))
      flash[:success] = 'Product updated'
      redirect_to product_path @product
    else
      render :edit
    end
  end

  def destroy
  end

  def new_specification
    @product = Product.find(params[:id])
    @product_specification = ProductSpecification.new
  end

  def create_specification
    @product = Product.find(params[:id])
    @product_specification = ProductSpecification.new(
      product_specification_params.merge({ product_id: @product.id }))

    if @product_specification.save
      flash[:success] = 'Specification added'
      redirect_to product_path @product
    else
      render :new
    end
  end

  def edit_specification
    @product = Product.find(params[:product_id])
    @product_specification = ProductSpecification.find(params[:specification_id])

    # Edit Breadbrumb Section
    @breadcrumb_components.last[:name] = "Edit #{@product_specification.key}"
    @breadcrumb_components[2][:name] = @product.name
    @breadcrumb_components.delete_at(-3)
    @breadcrumb_components.delete_at(-2)
  end

  def update_specification
    @product = Product.find(params[:product_id])
    @product_specification = ProductSpecification.find(params[:specification_id])

    if @product_specification.update_attributes(product_specification_params)
      flash[:success] = 'Specification updated'
      redirect_to product_path @product
    else
      render :edit_specification
    end
  end

  def index_specification
    @product = Product.find(params[:id])
  end

  def destroy_specification
  end

  def new_image
    @product = Product.find(params[:id])
    @product_image = ProductImage.new
  end

  def create_image
    @product = Product.find(params[:id])

    @image = @product.product_images.build(product_image_params)

    if @image.save
      flash[:success] = 'Image created'
      redirect_to product_path @product
    else
      render :new_image
    end
  end

  def edit_image
    @product = Product.find(params[:product_id])
    @product_image = ProductImage.find(params[:image_id])
  end

  def update_image
    @product = Product.find(params[:product_id])
    @product_image = ProductImage.find(params[:image_id])

    if @product_image.update_attributes(product_image_params)
      flash[:success] = 'Image updated'
      redirect_to product_path @product
    else
      render :edit_image
    end
  end

  def destroy_image
    @product = Product.find(params[:product_id])
    @product_image = ProductImage.find(params[:image_id])

    @product_image.destroy

    redirect_to request.referrer
  end

  private

    def product_params
      params.require(:product).permit(:name, :introduction, :description,
                                      :specification)
    end

    def product_specification_params
      params.require(:product_specification).permit(:key, :value)
    end

    def product_image_params
      params.require(:product_image).permit(:alt_text, :image)
    end
end

app/views/products/edit.html.erb
<section class="section-4 edit-product-form-container">
  <div class="container">
    <%= form_for @product, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <label class="col-sm-2 control-label">Author</label>
        <div class="col-sm-10">
          <p class="form-control-static">
            <%= current_user.name %>
          </p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Images</label>
        <div class="col-sm-10">
          <% @product.product_images.each do |product_image| %>
            <div class="image-container">
              <%= link_to product_edit_image_path(@product, product_image)do %>
                <%= image_tag product_image.image.url, width: 100, data: { toggle: :tooltip, placement: :top }, title: 'Click to Edit Image'  %>
              <% end %>

              <%= link_to 'Delete Image', product_delete_image_path(@product, product_image), class: 'text-danger', method: :delete %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :introduction, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :introduction, rows: 8, class: 'form-control', id: 'editor', placeholder: 'Product Introduction' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 8, class: 'form-control', id: 'editor_2', placeholder: 'Product Description' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Update Product", class: 'btn btn-bg bg-sea' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/products/edit_image.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for [@product, @product_image], class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :alt_text, 'Alt Text', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :alt_text, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :image, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Update' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/products/edit_specification.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for [@product, @product_specification], class: 'form' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :key, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :key, auto_focus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :value, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :value, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Update', class: 'btn btn-bg bg-sea form-button' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/products/index.html.erb
<section class="shop-section section-4">
  <div class="container">
    <div class="row">
      <% if user_signed_in? %>
        <div class="pull-right">
          <%= link_to products_new_path, class: 'btn btn-bg bg-green' do %>
            <i class="fa fa-plus"></i>
            New Product
          <% end %>
        </div>
      <% end %>

      <div class="col-sm-12">
        <div class="row shop-products">
          <% @products.each do |product| %>
            <a href="<%= product_path(product) %>">
              <div class="col-sm-6 col-md-4 col-lg-3">
                <figure class="shop-product">
                  <div class="shop-image">
                    <%= image_tag product.product_images.first.image.url %>
                    <div class="shop-actions">
                      <p><%= truncate strip_tags(@markdown.render(product.description).html_safe) %></p>
                      <%= link_to product_path(product), class: 'btn voyo-btn see', title: 'See details', data: { toggle: 'tooltip' } do %>
                        <i class="fa fa-search"></i>
                      <% end %>&nbsp;
                    </div>
                  </div>
                  <figcaption class="shop-description">
                    <h4><%= link_to product.name, product_path(product) %></h4>
                  </figcaption>
                </figure>
              </div>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @product, class: 'form-horizontal' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <label class="col-sm-2 control-label">Author</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= current_user.name %></p>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :introduction, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :introduction, rows: 8, class: 'form-control', id: 'editor', placeholder: 'Product Introduction' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 8, class: 'form-control', id: 'editor_2', placeholder: 'Product Description' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Add Product", class: 'btn btn-bg bg-sea' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/products/new_image.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for [@product, @product_image], class: 'form' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :alt_text %>
      <%= f.text_field :alt_text, auto_focus: true, class: 'form-control' %>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

      <%= f.submit 'Add Image' %>
    <% end %>
  </div>
</section>

app/views/products/new_specification.html.erb
<section class="section-4">
  <div class="container">
    <%= form_for @product_specification, class: 'form-horizontal' do |f| %>
      <div class="form-group">
        <%= f.label :key, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :key, class: 'form-control', placeholder: 'Key' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :value, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :value, class: 'form-control', placeholder: 'Value' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Add Specification" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/products/show.html.erb
<section class="shop-section section-4">
  <div class="container">
    <% if user_signed_in? %>
      <div class="pull-right">
        <%= link_to product_add_image_path, class: 'btn btn-bg bg-green' do %>
          <i class="fa fa-plus"></i>
          Add Product Image
        <% end %>

        <%= link_to product_edit_path, class: 'btn btn-bg bg-sea' do %>
          <i class="fa fa-pencil"></i>
          Edit Product
        <% end %>
      </div>

    <% end %>

    <div class="row mb35">
      <div class="col-sm-5">
        <div id="owl-shop" class="owl-carousel">
          <% @product.product_images.order('created_at asc').each do |product_image| %>
            <div class="owl-item-shop zoom">
              <% if product_image.image_file_name %>
                <%= image_tag product_image.image.url %>
              <% elsif user_signed_in? %>
                <%= link_to product_edit_image_path(@product, product_image) do %>
                  <%= image_tag '//cumbrianrun.co.uk/wp-content/uploads/2014/02/default-placeholder.png' %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <% @product.product_images.each_with_index do |product_image, index| %>
            <%= link_to "Edit Image #{index + 1}", product_edit_image_path(@product, product_image) %><br>
          <% end %>
        <% end %>
      </div>
      <div class="col-sm-7">
        <div class="shop-description-product">
          <h3><%= @product.name %></h3>
          <%= @markdown.render(@product.introduction).html_safe %>
        </div>
      </div>
    </div>
    <div class="row mb20">
      <div class="col-sm-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Product Description</a></li>
          <li><a href="#tab2" data-toggle="tab">Product Specifications</a></li>
          <li><a href="#tab3" data-toggle="tab">Product Reviews</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane fade in active shop-long-description-product" id="tab1">
            <%= @markdown.render(@product.description).html_safe %>
          </div>
          <div class="tab-pane fade shop-specifications" id="tab2">
            <% if user_signed_in? %>
              <div class="pull-right">
                <%= link_to 'Add Specification', product_add_specification_path(@product), class: 'btn btn-bg bg-sea' %>
              </div>
            <% end %>

            <table class="table table-bordered product-specs-table">
              <thead>
                <tr>
                  <th>Key</th>
                  <th>Value</th>
                  <% if user_signed_in? %>
                    <th class="actions">Actions</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @product.product_specifications.each do |specification| %>
                  <tr>
                    <td><%= specification.key %></td>
                    <td><%= specification.value %></td>
                    <% if user_signed_in? %>
                      <td>
                        <%= link_to 'Edit', product_edit_specification_path(@product, specification) %> |
                        <%= link_to 'Delete', product_delete_specification_path(@product, specification) %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="tab3">
            <% if @product.product_reviews.any? %>
              <div class="shop-reviews">
                <% @product.product_reviews.each do |review| %>
                  <div class="shop-comment">
                    <% if user_signed_in? %>
                      <div class="pull-right">
                        <%= link_to delete_product_review_path(@product, review), class: 'btn btn-bg bg-red' do %>
                          Delete
                        <% end %>
                      </div>
                    <% end %>

                    <div class="author">
                      <cite><%= review.name %></cite>
                      <span class="date"><%= review.created_at.strftime("%e %b %Y, at %I:%M%P") %></span>
                    </div>
                    <div class="rating-system rate-review"><%= pluralize(review.rating, 'star') %></div>
                    <p><%= review.body %></p>
                  </div>
                <% end %>
              </div>
            <% else %>
              <p class="center"><%= edit_text(@page, 'product_page_no_reviews_helper', 'There are no reviews for this product, be the first to review it below!') %></p>
            <% end %>

            <%= form_for [@product, @review], class: 'form' do |f| %>
              <%= render 'shared/error_messages', object: f.object %>

              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, auto_focus: true, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :body, 'Review' %>
                <%= f.text_area :body, rows: 5, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :rating %>
                <%= f.select :rating, 1..5, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.submit 'Create' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>